# Generated by Django 3.2.7 on 2021-10-08 15:54

from django.db import migrations
import formation.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('generic_list', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('block_id', formation.blocks.IDBlock(label='--', required=False)), ('fields', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock())])), ('container', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock())])))]))]))), ('stream', wagtail.core.blocks.StreamBlock([('form', wagtail.core.blocks.StructBlock([('block_id', formation.blocks.IDBlock(label='--', required=False)), ('fields', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock())])), ('container', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock())])))]))]))])), ('form', wagtail.core.blocks.StructBlock([('block_id', formation.blocks.IDBlock(label='--', required=False)), ('fields', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock())])), ('container', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock())])))]))]))], default=''),
            preserve_default=False,
        ),
    ]
